name: tm
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.5
  - matplotlib=3.10.0
  - numpy=1.26.4
  - pandas=2.2.3
  - pip=25.1
  - python>=3.12
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - pip:
      - accelerate==1.7.0
      - gensim==4.3.3
      - keras==3.10.0
      - nltk==3.9.1
      - scipy==1.13.1
      - tensorflow==2.19.0
      - torch==2.7.0
      - tqdm==4.67.1
      - transformers==4.52.4
      - types-tensorflow
      - wordcloud==1.9.4
      - emoji
      - pycountry
      - contractions
      - dateparser
      - geotext
